### ISSUE TITLE
Question about the android client features

### ISSUE THREAD

**Issue by ovizii** [sndnv/stasis#35]
Sorry to post my question as an issue, but you haven't enabled discussion on this project. 

Would you mind giving some details about the clients features? 
I’ve read how secure and private all of this is, but I have yet to find a single detail about what type of data the android client can actually back up?

Is it just apps and their respective data? 
Can it backup say my wifi settings and credentials too?
Does it make any difference whether my phone is rooted or not?

And when it comes to the other operating systems like linux, would you mind comparing your solution to some established solutions like restic or borg?

I will spin up your docker-ciompose.yml and have a look but I'd appreciate more info too.

**Comment by sndnv** [comment]
Hi @ovizii

Thanks for your questions; indeed, I didn't document this stuff in any detail :)

The clients, both Android and Linux/macOS, only deal with file systems and files, so the access that your user has determines which files the client is _allowed_ to backup/recover. On top of that, there are the backup rules that define which files you _want_ to backup. Both of these then determine what actually ends up on the server as your backup entry.

For Android specifically, things get a bit more complicated; the app is requesting the [`MANAGE_EXTERNAL_STORAGE`](https://developer.android.com/training/data-storage/manage-all-files#all-files-access) permission so most user data should be accessible but there are some exceptions (see the link for more info).

Now for some of the more specific questions:

**_Is it just apps and their respective data?_** - The client doesn't explicitly try to collect apps or their data; so it depends on the backup rules and the user permissions
**_Can it backup say my wifi settings and credentials too?_** - Same as above, basically; I actually don't know where/how these things are stored so I can't say if it will work but I suspect it will not since it's quite sensitive data. You could try to find where Android saves this, point the client to those files and see what happens :sweat_smile: 
**_Does it make any difference whether my phone is rooted or not?_** - A rooted phone is not required but it will have an impact on what the client can access, if you are running the app as root. In that case, I expect everything to be accessible but I haven't tested this myself. _I would approach this with caution though; the client does not care what files it's recovering, it just does it. So it could be that some system files need to be handled in a special way during recovery and when the client doesn't do that, you might end up with a bricked phone!_ :smile:

For the comparison to other tools, I never looked myself but it would be interesting; I'll try to do that later.

Do let me know how it goes with the docker-compose; setting up the services is not trivial so I'm curious how it will go for somebody that's not familiar with the project.

**Comment by ovizii** [comment]
Ah, I see, thanks for clarifying all of that. It looks like this is not the type of tool I was looking for. Sounds like this is meant to back up “user data” – not sure how I can describe this better. 

I settled for a specific backup tool for Android which (due to being rooted) lets me back up all the settings, wifi, accounts, etc. as well as simply select an app and have it and all of its accompanying data backed up. This backup gets replicated off-site on my NAS via rclone.

I don't actually have any data on my phone which falls under what I earlier described as "user data" – meaning music, pictures, documents, all these I either immediately sync to my NAS or access straight over the internet.
